name: 'Control changed files'
on:
  pull_request:
    branches:
      master
inputs:
  changed-files:
    description: 'All changed files in pull request'
    required: true
  nesting:
    description: 'Number of nested folders to ignore'
    required: false
    default: 0
runs:
  using: 'node16'
  main: 'dist/index.js'