name: 'Control changed files'
on:
  pull_request:
    branches:
      master
inputs:
  changed-files:  # id of input
    description: 'All changed files in pull request'
    required: true
  nesting:
    description: 'Number of nested folders to ignore'
    required: false
    default: '0'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'