on:
  pull_request:
    branches:
    - master

jobs:
  control-changed-files:
    name: control changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: get-paths
        run: | 
          echo "JSON=$(gh pr view XXX --json files -q '.files[].path')" >> GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check changed files
        uses: ./
        with:
          changed-files: ${{steps.get-paths.outputs.JSON}}

      

      