on:
  pull_request:
    branches:
    - master

jobs:
  control-changed-files:
    name: control changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
      - name: Check changed files
        uses: ./
        with:
          changed-files: ${{steps.changed-files.outputs.all_changed_files}}

      

      